spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/fraud_detector}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.listener.auto-startup=true

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

ml.service.url=${ML_SERVICE_URL:http://ml-service:8001}

kafka.producer.fallback-to-direct=false

app.security.api-key=${APP_API_KEY:}
