import os
import json
import joblib
import numpy as np
import pandas as pd

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from typing import List

from app.schemas import MLScoreRequest, MLScoreResponse
from app.preprocessing import transform_transaction
from app.scoring import score_ensemble
from app.explain import (
    generate_rule_reasons,
    compute_shap_explanations,
    init_shap_explainer
)


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Fraud Anomaly Detection ML Service",
    description=(
        "Microservice providing real-time ensemble fraud "
        "scoring and SHAP explainability"
    ),
    version="1.0.0"
)


# ============================================================
# CORS CONFIGURATION
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# MODEL DIRECTORY
# ============================================================

MODELS_DIR = os.path.join(
    os.path.dirname(
        os.path.dirname(__file__)
    ),
    "models"
)


# ============================================================
# LOAD TRAINED MODELS
# ============================================================

def load_models():

    # --------------------------------------------------------
    # Gradient Boosting
    # --------------------------------------------------------

    gb_path = os.path.join(
        MODELS_DIR,
        "gb_model.pkl"
    )

    # Support the actual filename generated by train_model.py
    if not os.path.exists(gb_path):

        gb_path = os.path.join(
            MODELS_DIR,
            "gradient_boost.pkl"
        )


    # --------------------------------------------------------
    # Isolation Forest
    # --------------------------------------------------------

    iso_path = os.path.join(
        MODELS_DIR,
        "isolation_forest.pkl"
    )


    # --------------------------------------------------------
    # Feature columns
    # --------------------------------------------------------

    cols_path = os.path.join(
        MODELS_DIR,
        "feature_cols.pkl"
    )


    gb = (
        joblib.load(gb_path)
        if os.path.exists(gb_path)
        else None
    )


    iso = (
        joblib.load(iso_path)
        if os.path.exists(iso_path)
        else None
    )


    cols = (
        joblib.load(cols_path)
        if os.path.exists(cols_path)
        else [
            "amount",
            "oldbalanceOrg",
            "newbalanceOrig",
            "oldbalanceDest",
            "newbalanceDest",
            "balanceDiffOrig",
            "balanceDiffDest",
            "origBalanceZero",
            "destBalanceZero",
            "type_CASH_IN",
            "type_CASH_OUT",
            "type_DEBIT",
            "type_PAYMENT",
            "type_TRANSFER"
        ]
    )


    # --------------------------------------------------------
    # Autoencoder
    # --------------------------------------------------------

    ae = None
    ae_scaler = None   # dict: {min, range, threshold}

    ae_path = os.path.join(
        MODELS_DIR,
        "autoencoder.pt"
    )

    if os.path.exists(ae_path):

        try:

            import torch
            import torch.nn as nn

            checkpoint = torch.load(ae_path, map_location="cpu")

            # New format: state_dict dict saved by train_autoencoder.py
            if isinstance(checkpoint, dict) and "model_state" in checkpoint:

                input_dim = checkpoint["input_dim"]

                class _AE(nn.Module):
                    def __init__(self):
                        super().__init__()
                        self.encoder = nn.Sequential(
                            nn.Linear(input_dim, 16), nn.ReLU(),
                            nn.Linear(16, 8),          nn.ReLU(),
                            nn.Linear(8, 4),           nn.ReLU()
                        )
                        self.decoder = nn.Sequential(
                            nn.Linear(4, 8),           nn.ReLU(),
                            nn.Linear(8, 16),          nn.ReLU(),
                            nn.Linear(16, input_dim),  nn.Sigmoid()
                        )
                    def forward(self, x):
                        return self.decoder(self.encoder(x))

                _model = _AE()
                _model.load_state_dict(checkpoint["model_state"])
                _model.eval()
                ae = _model

                ae_scaler = {
                    "min":       np.array(checkpoint["feat_min"],   dtype=np.float32),
                    "range":     np.array(checkpoint["feat_range"], dtype=np.float32),
                    "threshold": float(checkpoint.get("threshold", 0.05))
                }

            else:
                # Legacy format: full model object
                ae = checkpoint

        except Exception as e:
            print(f"[WARN] Could not load autoencoder: {e}")
            ae = None
            ae_scaler = None

    return (
        gb,
        iso,
        cols,
        ae,
        ae_scaler
    )


# Load models once when FastAPI starts

gb_model, iso_forest, feature_cols, autoencoder, ae_scaler = (
    load_models()
)

if gb_model is not None:
    init_shap_explainer(gb_model)


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/")
@app.get("/health")
def health_check():

    return {

        "status": "healthy",

        "service": (
            "Real-Time Fraud Anomaly ML Service"
        ),

        "models_loaded": {

            "gradient_boosting":
                gb_model is not None,

            "isolation_forest":
                iso_forest is not None,

            "autoencoder":
                autoencoder is not None
        }
    }


# ============================================================
# REAL MODEL EVALUATION METRICS
# ============================================================

@app.get("/model-metrics")
def get_model_metrics():

    # evaluation_metrics.json is generated
    # by train_model.py after real model evaluation.

    metrics_path = os.path.join(
        MODELS_DIR,
        "evaluation_metrics.json"
    )


    # --------------------------------------------------------
    # Check metrics file exists
    # --------------------------------------------------------

    if not os.path.exists(
        metrics_path
    ):

        raise HTTPException(
            status_code=404,
            detail=(
                "Model evaluation metrics not found. "
                "Run train_model.py first."
            )
        )


    # --------------------------------------------------------
    # Read real evaluation metrics
    # --------------------------------------------------------

    try:

        with open(
            metrics_path,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(
                file
            )


        return metrics


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                "Unable to load model metrics: "
                f"{str(e)}"
            )
        )


# ============================================================
# SINGLE TRANSACTION SCORING
# ============================================================

@app.post(
    "/score",
    response_model=MLScoreResponse
)
def score_transaction_endpoint(
    txn: MLScoreRequest
):

    # --------------------------------------------------------
    # Verify required models
    # --------------------------------------------------------

    if (
        gb_model is None
        or iso_forest is None
    ):

        raise HTTPException(
            status_code=500,
            detail=(
                "ML models not initialized"
            )
        )


    # --------------------------------------------------------
    # Convert request into model features
    # --------------------------------------------------------

    txn_dict = txn.model_dump()


    X_df = transform_transaction(
        txn_dict,
        feature_cols
    )


    # --------------------------------------------------------
    # Ensemble scoring
    # --------------------------------------------------------

    (
        gb_prob,
        iso_score,
        is_anomaly,
        ae_mse,
        blended_score,
        risk_level

    ) = score_ensemble(

        X_df,
        gb_model,
        iso_forest,
        autoencoder,
        ae_scaler
    )


    # --------------------------------------------------------
    # Rule-based explainability
    # --------------------------------------------------------

    rule_reasons = (
        generate_rule_reasons(
            X_df,
            txn_dict
        )
    )


    # --------------------------------------------------------
    # SHAP explainability
    # --------------------------------------------------------

    shap_dict, shap_reasons = (
        compute_shap_explanations(
            gb_model,
            X_df
        )
    )


    # Remove duplicate reasons while
    # preserving original ordering.

    all_reasons = list(
        dict.fromkeys(
            rule_reasons
            + shap_reasons
        )
    )


    # --------------------------------------------------------
    # API response
    # --------------------------------------------------------

    ae_threshold = ae_scaler["threshold"] if ae_scaler else 0.05
    ae_status = "UNAVAILABLE" if autoencoder is None else "NORMAL"

    if autoencoder is not None and ae_mse > ae_threshold:
        ae_status = "HIGH"

    return MLScoreResponse(

        transaction_id=(
            txn.transaction_id
        ),

        gradient_boost_probability=round(
            gb_prob,
            4
        ),

        gradient_boost_risk_percent=round(
            gb_prob * 100,
            2
        ),

        isolation_forest_score=round(
            iso_score,
            4
        ),

        isolation_forest_anomaly=(
            is_anomaly
        ),

        autoencoder_mse=round(
            ae_mse,
            6
        ),

        autoencoder_status=ae_status,

        ensemble_risk_score=round(
            blended_score,
            4
        ),

        risk_level=(
            risk_level
        ),

        top_reasons=(
            all_reasons
        ),

        shap_values=(
            shap_dict
        )
    )


# ============================================================
# BATCH TRANSACTION SCORING
# ============================================================

@app.post(
    "/score/batch",
    response_model=List[MLScoreResponse]
)
def batch_score_endpoint(
    txns: List[MLScoreRequest]
):

    if len(txns) > 100:
        raise HTTPException(
            status_code=413,
            detail="Batch size exceeds maximum of 100 transactions"
        )

    return [
        score_transaction_endpoint(
            txn
        )
        for txn in txns
    ]