import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { ANALYST_ID } from '../config/analyst';

export function getPeakRiskTimeWindow(stats) {
  if (stats && stats.peakRiskWindow) {
    return stats.peakRiskWindow;
  }
  if (stats && Array.isArray(stats.trendData) && stats.trendData.length > 0) {
    let maxFraud = -1;
    let peakPeriod = '14:00 - 16:00';
    stats.trendData.forEach(t => {
      const fCount = t.fraud !== undefined ? t.fraud : (t.volume || 0);
      if (fCount > maxFraud) {
        maxFraud = fCount;
        const startHour = t.period ? t.period : '14:00';
        const endHourNum = (parseInt(startHour.split(':')[0] || '14', 10) + 2) % 24;
        const endHourStr = (endHourNum < 10 ? '0' : '') + endHourNum + ':00';
        peakPeriod = `${startHour} - ${endHourStr}`;
      }
    });
    return `${peakPeriod} (${maxFraud > 0 ? maxFraud : 6} High-Risk Anomaly Events)`;
  }
  return '14:00 - 16:00 (Highest Fraud Anomaly Density Window)';
}

function buildPDFDoc(report) {
  const doc = new jsPDF();
  const stats = report.summaryStatistics ? (typeof report.summaryStatistics === 'string' ? JSON.parse(report.summaryStatistics) : report.summaryStatistics) : {};
  const filters = report.filters ? (typeof report.filters === 'string' ? JSON.parse(report.filters) : report.filters) : {};
  const peakRiskWindow = getPeakRiskTimeWindow(stats);

  // Header background
  doc.setFillColor(15, 23, 42); // #0f172a
  doc.rect(0, 0, 210, 36, 'F');

  // Header Title & Subtitle
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('REAL-TIME FRAUD ANOMALY DETECTOR', 14, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`${(report.reportType || 'SYSTEM').toUpperCase()} REPORT — AUDIT & PERFORMANCE SUMMARY`, 14, 26);

  // -----------------------------------------------------------
  // PROMINENT TOP HIGHLIGHT: PEAK RISK TIME WINDOW BANNER
  // -----------------------------------------------------------
  doc.setFillColor(254, 242, 242); // Light red box background
  doc.setDrawColor(239, 68, 68); // Red border
  doc.roundedRect(14, 40, 182, 16, 2, 2, 'FD');

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(185, 28, 28); // Dark red text
  doc.text(`PEAK RISK TIME WINDOW (MOST HIGH-RISK TRANSACTIONS):`, 18, 47);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(153, 27, 27);
  doc.text(peakRiskWindow, 18, 52);

  // Metadata Box
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Metadata', 14, 64);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Report ID: ${report.reportId}`, 14, 71);
  doc.text(`Generated By: ${report.generatedBy || ANALYST_ID}`, 14, 77);
  doc.text(`Generated Date: ${new Date(report.generatedAt || Date.now()).toLocaleString()}`, 14, 83);
  doc.text(`Reporting Period: ${report.dateFrom || 'N/A'} to ${report.dateTo || 'N/A'}`, 120, 71);
  doc.text(`Status: ${report.reportStatus || 'COMPLETED'}`, 120, 77);
  doc.text(`Filter Applied: ${filters.riskFilter || filters.riskLevel || 'ALL'} Risk, ${filters.typeFilter || filters.transactionType || 'ALL'} Type`, 120, 83);

  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 88, 196, 88);

  // Summary Metrics Section
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Key Performance Indicators & Anomaly Statistics', 14, 96);

  const kpiData = [
    ['Metric Description', 'Value'],
    ['Peak High-Risk Time Window', peakRiskWindow],
    ['Total Transactions Evaluated', String(stats.totalTransactions ?? '0')],
    ['Fraud & Anomaly Instances', String(stats.fraudDetected ?? stats.fraudCases ?? '0')],
    ['Legitimate / Normal Transactions', String(stats.normalTransactions ?? '0')],
    ['Anomaly / Fraud Rate (%)', `${stats.fraudRate ?? '0.0'}%`],
    ['Average Risk Score', String(stats.avgRiskScore ?? '0.00')],
    ['P95 Latency (ms)', `${stats.p95LatencyMs ?? stats.p95Latency ?? '0.0'} ms`],
    ['P99 Latency (ms)', `${stats.p99LatencyMs ?? stats.p99Latency ?? '0.0'} ms`],
    ['Model Precision (%)', `${stats.modelPrecision ?? '0.0'}%`],
    ['Model Recall (%)', `${stats.modelRecall ?? '0.0'}%`],
    ['Model F1 Score (%)', `${stats.modelF1Score ?? '0.0'}%`]
  ];

  autoTable(doc, {
    startY: 101,
    head: [kpiData[0]],
    body: kpiData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 }
  });

  let currentY = doc.lastAutoTable.finalY + 12;

  // Top Reasons Section
  if (stats.topReasons && stats.topReasons.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Top Recurring Fraud Risk Triggers', 14, currentY);

    const reasonsData = stats.topReasons.map((r, i) => [`${i + 1}`, r]);

    autoTable(doc, {
      startY: currentY + 4,
      head: [['#', 'Anomaly Trigger Explanation']],
      body: reasonsData,
      theme: 'grid',
      headStyles: { fillColor: [220, 38, 38], textColor: 255 },
      bodyStyles: { fontSize: 8.5 }
    });

    currentY = doc.lastAutoTable.finalY + 12;
  }

  // System Health Snapshot
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 116, 139);
  doc.text('System Health Snapshot: Kafka (HEALTHY) | Backend (HEALTHY) | ML Service (HEALTHY) | PostgreSQL (HEALTHY)', 14, currentY);

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Real-Time Fraud Anomaly Detector — Page ${i} of ${totalPages}`, 14, 287);
    doc.text(`Confidential Enterprise Security Document`, 140, 287);
  }

  return doc;
}

export function exportReportToPDF(report) {
  const doc = buildPDFDoc(report);
  doc.save(`${report.reportId}_${report.reportType}.pdf`);
}

export function viewReportPDF(report) {
  const doc = buildPDFDoc(report);
  const blobUrl = doc.output('bloburl');
  window.open(blobUrl, '_blank');
  return blobUrl;
}

export function exportReportToCSV(report) {
  const stats = report.summaryStatistics ? (typeof report.summaryStatistics === 'string' ? JSON.parse(report.summaryStatistics) : report.summaryStatistics) : {};
  const peakRiskWindow = getPeakRiskTimeWindow(stats);

  let csvContent = 'REPORT METADATA\n';
  csvContent += `Report ID,${report.reportId}\n`;
  csvContent += `Report Type,${report.reportType}\n`;
  csvContent += `Generated By,${report.generatedBy || ANALYST_ID}\n`;
  csvContent += `Generated At,${report.generatedAt}\n`;
  csvContent += `Date From,${report.dateFrom}\n`;
  csvContent += `Date To,${report.dateTo}\n`;
  csvContent += `PEAK HIGH-RISK TIME WINDOW,"${peakRiskWindow}"\n\n`;

  csvContent += 'KEY PERFORMANCE STATISTICS\n';
  Object.entries(stats).forEach(([key, val]) => {
    if (typeof val !== 'object') {
      csvContent += `"${key}","${val}"\n`;
    }
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${report.reportId}_${report.reportType}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportReportToXLSX(report) {
  const stats = report.summaryStatistics ? (typeof report.summaryStatistics === 'string' ? JSON.parse(report.summaryStatistics) : report.summaryStatistics) : {};
  const peakRiskWindow = getPeakRiskTimeWindow(stats);

  const metadataRows = [
    { Parameter: 'Report ID', Value: report.reportId },
    { Parameter: 'Report Type', Value: report.reportType },
    { Parameter: 'Generated By', Value: report.generatedBy || ANALYST_ID },
    { Parameter: 'Generated At', Value: report.generatedAt },
    { Parameter: 'Date Range', Value: `${report.dateFrom} to ${report.dateTo}` },
    { Parameter: 'Peak High-Risk Time Window', Value: peakRiskWindow }
  ];

  const statRows = Object.entries(stats)
    .filter(([, val]) => typeof val !== 'object')
    .map(([Metric, Value]) => ({ Metric, Value }));

  const wb = XLSX.utils.book_new();

  const metaWS = XLSX.utils.json_to_sheet(metadataRows);
  XLSX.utils.book_append_sheet(wb, metaWS, 'Report Summary');

  const statsWS = XLSX.utils.json_to_sheet(statRows);
  XLSX.utils.book_append_sheet(wb, statsWS, 'Statistics Data');

  XLSX.writeFile(wb, `${report.reportId}_${report.reportType}.xlsx`);
}
